blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog import views

urlpatterns = [
    path('', views.Blog_list.as_view(), name='home'),
    path('blog/<str:slug>/', views.Blog_detail.as_view(), name='detail'),
    ]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/ap/', views.dashboard_ap, name='dashboard_ap'),
    path('dashboard/tr/', views.dashboard_tr, name='dashboard_tr'),
    path('dashboard/check-suggest/<int:sentence_id>', views.check_suggest, name="check_suggest"),
    path('dashboard/<int:sentence_id>/<str:sentence_title>', views.sentence_detail_dashboard,
         name="sentence_detail_dashboard")
    ]

davari/urls.py
from django.urls import path

from davari import views


app_name = 'davari'

urlpatterns = [
    path('dashboard/da/', views.dashboard_da, name='dashboard_da'),
    path('dashboard/da/<int:suggest_id>', views.sentence_detail_davari,
         name="sentence_detail_davari"),

    ]

onesentence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
# if settings.DEBUG:
#     import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('business.urls')),
    path('', include('dashboard.urls')),
    path('', include('davari.urls')),
    path('', include('payment.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

# urlpatterns += [
#     url(r'^__debug__/', include(debug_toolbar.urls)),
# ]

davari/models.py
from django.db import models
from business.models import Suggest
from django.contrib.auth.models import User




davari/forms.py
from django import forms
from business import models


class UpdateJudgmentForm(forms.ModelForm):
    class Meta:
        model = models.Judgment
        fields = ('judgment_won_user', 'mablagh', 'davar_description')

davari/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from business.models import Judgment, Dashboard
from davari.forms import UpdateJudgmentForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from decimal import Decimal


@login_required
def dashboard_da(request):
    judgments = Judgment.objects.all()
    return render(request, "davar_dashboard.html", {'judgments': judgments})


@login_required
def sentence_detail_davari(request, suggest_id):
    judgment = get_object_or_404(Judgment, suggest_id=suggest_id)
    sentence = judgment.suggest.sentence
    user_applicant = sentence.user
    user_translator = sentence.translator
    if request.method == "POST":
        judgment_form = UpdateJudgmentForm(request.POST, instance=judgment)
        mablagh = request.POST.get('mablagh')
        if judgment_form.is_valid():
            judgment_form = judgment_form.save(commit=False)
            judgment_form.save()

            if user_applicant == judgment.judgment_won_user:
                user_loser = user_translator
            else:
                user_loser = user_applicant

            # todo log transactions
            mojodi_won_user = Dashboard.objects.get(user=judgment.judgment_won_user).mojodi
            mojodi_lose_user = Dashboard.objects.get(user=user_loser).mojodi

            Dashboard.objects.filter(user=judgment.judgment_won_user).update(mojodi=mojodi_won_user + Decimal(mablagh))
            Dashboard.objects.filter(user=user_loser).update(mojodi=mojodi_lose_user - Decimal(mablagh))
            return redirect("business:home")
    else:
        judgment_form = UpdateJudgmentForm(instance=judgment)
    return render(request, "sentence_detail_davari.html", {'judgment': judgment,
                                                           'judgment_form': judgment_form})

davari/templates/davar_dashboard.html
{% extends 'base.html' %}
{% block title %} onesentence - خانه {% endblock %}
{% block content %}

    <h1>داشبورد داور</h1>

    <table border="1">
     <thead>
        <td>
         کد جمله
        </td>
        <td>
          عنوان
        </td>
        <td>
         زمان ثبت
        </td>
        <td>
            درخواست داوری از
        </td>
        <td>
            توضیحات
        </td>
        <td>
          وضعیت پیشنهاد
        </td>
        <td>
            رای به نفع
        </td>
     <td>
         بررسی درخواست
     </td>
     </thead>
     <tbody>
     {% for judgment in judgments %}
        <tr>
            <td>
             {{ judgment.suggest.sentence.id }}
            </td>
           <td>
               <a href="{% url 'dashboard:sentence_detail_dashboard' judgment.suggest.sentence.id judgment.suggest.sentence.title %}">{{ judgment.suggest.sentence.title }} </a>
           </td>
           <td>
            {{ judgment.suggest.sentence.create_time }}
           </td>
            <td>
                <a href="#"> {{ judgment.judgment_user }} </a>
            </td>
            <td>
                {{ judgment.judgment_description }}
            </td>
           <td>
            {{ judgment.suggest.status }}
           </td>
            <td>
                {{ judgment.judgment_won_user }}
            </td>
            <td>
                {% if judgment.judgment_won_user %}
                 -
                {% else %}
                <a href=" {% url 'davari:sentence_detail_davari' judgment.suggest.id%}">
                    بررسی درخواست</a>
                {% endif %}
            </td>
     </tr>
     {% endfor %}
     </tbody>
    </table>

{% endblock %}

davari/templates/sentence_detail_davari.html
{% extends 'base.html' %}
{% block title %} onesentence - جزییات جمله {% endblock %}
{% block content %}

    <h1>جزییات جمله</h1>
    <hr />
    <div style="border:1px solid gray; margin:15px;">
        عنوان:
        <a href="#">{{ judgment.suggest.sentence.title }}</a>
        <br />
        متن اصلی:
        <span> {{judgment.suggest.sentence.content_text}} </span>
        <br />
        زمان ثبت:
        <span>{{ judgment.suggest.sentence.create_time }}</span>
        <br />
        تخصص:
        <span> {{judgment.suggest.sentence.takhasos.title }} </span>
        <br />
        تعداد کاراکترها:
        <span> {{judgment.suggest.sentence.word_count}} </span>
        <br />
        درخواست کننده:
        <a href="#"> {{judgment.suggest.sentence.user}} </a>
        <br />
        مهلت انجام:
        <span> {{judgment.suggest.sentence.mohlat_rooz }} روز</span>
        <span> {{judgment.suggest.sentence.mohlat_saat }} ساعت</span>
        <br />
        <span class="status">وضعیت جمله:</span>
        <span class="status">{{ judgment.suggest.sentence.status }}</span>
            <h3>پیشنهاد تایید شده
            </h3>
            <div style="background-color:lightgray; margin:5px; padding:5px;">
                    مجری:
                    <span>{{ judgment.suggest.mojri }}</span>
                    <br />
                    مبلغ پیشنهادی:
                    <span>{{ judgment.suggest.mablagh_pishnahadi }}</span>
                    <br />
                    توضیحات:
                    <span>{{ judgment.suggest.description }}</span>
                    <br />
                    فایل تحویلی:
                    <span>{{ judgment.suggest.completeFile }}</span>
            </div>
            <h3>درخواست داوری</h3>
                    <div  style="background-color:lightgray; margin:5px; padding:5px;">
                        درخواست کننده:
                        {{ judgment.judgment_user }}
                        <br/>
                        تاریخ ثبت:
                        {{ judgment.create_time }}
                        <br/>
                        توضیحات:
                        {{ judgment.judgment_description }}
                        <br/>
                        رای داور به نفع:
                        {{ judgment.judgment_won_user }}
                    </div>

                    <form method="post" action="">
                        {% csrf_token %}
                        {{ judgment_form.as_p }}
                        <input type="submit" name="judgment_btn" value="ثبت کاربر برنده"/>
                    </form>
    </div>

{% endblock %}