blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog import views

urlpatterns = [
    path('', views.Blog_list.as_view(), name='home'),
    path('blog/<str:slug>/', views.Blog_detail.as_view(), name='detail'),
    ]

business/urls.py
from django.urls import path
from business import views
from django.contrib.auth import views as auth_views

from .api.router import router
from .api.views import SentenceList, SentenceDetail, AddSentence


app_name = 'business'

urlpatterns = [
    path('', views.home, name='home'),
    path('add_sentence/', views.add_sentence, name='add_sentence'),
    # path('submit_suggest/', views.submit_suggest, name='submit_suggest'),
    path('sentence_list/', views.SentenceList.as_view(), name='sentence_list'),
    path('sentence/<int:sentence_id>/<str:sentence_title>', views.sentence_detail, name='sentence_detail'),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),

    path('api/v1/sentence-list/', SentenceList.as_view(), name='sentence_list_api'),
    path('api/v1/sentence-detail/<int:pk>/', SentenceDetail.as_view(), name='sentence_detail_api'),
    path('api/v1/add-sentence/', AddSentence.as_view(), name='add_sentence_api'),
    ]

# urlpatterns += router.urls


dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/ap/', views.dashboard_ap, name='dashboard_ap'),
    path('dashboard/tr/', views.dashboard_tr, name='dashboard_tr'),
    path('dashboard/check-suggest/<int:sentence_id>', views.check_suggest, name="check_suggest"),
    path('dashboard/<int:sentence_id>/<str:sentence_title>', views.sentence_detail_dashboard,
         name="sentence_detail_dashboard")
    ]

davari/urls.py
from django.urls import path

from davari import views


app_name = 'davari'

urlpatterns = [
    path('dashboard/da/', views.dashboard_da, name='dashboard_da'),
    path('dashboard/da/<int:suggest_id>', views.sentence_detail_davari,
         name="sentence_detail_davari"),

    ]

onesentence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
# if settings.DEBUG:
#     import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('business.urls')),
    path('', include('dashboard.urls')),
    path('', include('davari.urls')),
    path('', include('payment.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

# urlpatterns += [
#     url(r'^__debug__/', include(debug_toolbar.urls)),
# ]

payment/urls.py
from django.urls import path

from payment import views


app_name = 'payment'

urlpatterns = [
    path('payment/', views.init_pay, name='init_pay'),
    path('callback/', views.callback, name='callback'),
    path('charge/', views.charge, name='charge')
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Base {% endblock %}</title>
    <style type="text/css">
        .status{
        font-weight:bold;

        }
    </style>
</head>
<body dir="rtl">
    <ul>
        <li><a href="{% url 'business:home'%}">خانه</a></li>
        <li><a href="{% url 'dashboard:dashboard_ap'%}">داشبورد درخواست کننده</a></li>
        <li><a href="{% url 'dashboard:dashboard_tr'%}">داشبورد مترجم</a></li>
        <li><a href="{% url 'davari:dashboard_da'%}">داشبورد داور</a></li>
        <li><a href="{% url 'business:add_sentence'%}">ثبت جمله</a></li>
        <li><a href="{% url 'business:sentence_list'%}">لیست جمله ها</a></li>
        <li><a href="{% url 'payment:charge'%}">افزایش اعتبار</a> </li>
        {% if request.user.is_authenticated %}
            <a href="{% url 'business:logout' %}">خروج</a>
        {% endif %}
    </ul>
    {% block content %}

    {% endblock %}
</body>
</html>