blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog import views

urlpatterns = [
    path('', views.Blog_list.as_view(), name='home'),
    path('blog/<str:slug>/', views.Blog_detail.as_view(), name='detail'),
    ]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/ap/', views.dashboard_ap, name='dashboard_ap'),
    path('dashboard/tr/', views.dashboard_tr, name='dashboard_tr'),
    path('dashboard/check-suggest/<int:sentence_id>', views.check_suggest, name="check_suggest"),
    path('dashboard/<int:sentence_id>/<str:sentence_title>', views.sentence_detail_dashboard,
         name="sentence_detail_dashboard")
    ]

onesentence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
# if settings.DEBUG:
#     import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('business.urls')),
    path('', include('dashboard.urls')),
    path('', include('davari.urls')),
    path('', include('payment.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

# urlpatterns += [
#     url(r'^__debug__/', include(debug_toolbar.urls)),
# ]

dashboard/forms.py
from django import forms
from business import models


class EditCompleteFileForm(forms.ModelForm):
    class Meta:
        model = models.Suggest
        fields = ('completeFile',)


class SubmitJudgmentForm(forms.ModelForm):
    class Meta:
        model = models.Judgment
        fields = ('judgment_description',)


class ChargeForm(forms.Form):
    mablagh = forms.IntegerField(label='مبلغ (تومان)', min_value=1000, max_value=1000000)

    def clean_mablagh(self):
        mablagh = self.cleaned_data['mablagh']
        if mablagh < 1000 or mablagh > 1000000:
            raise forms.ValidationError('مبلغ وارد شده معتبر نیست.')

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from business.models import Suggest, Sentence, Judgment
import logging
from django.db.models import Count
from django.shortcuts import redirect
from onesentence.enums import SuggestEnum, SentenceEnum
from dashboard.forms import EditCompleteFileForm, SubmitJudgmentForm
import datetime

logger = logging.getLogger(__name__)


@login_required
def dashboard_ap(request):
    my_sentence = Sentence.objects.annotate(num_suggests=Count('suggest')).filter(
        user=request.user)
    return render(request, 'applicant_dashboard.html', {'my_sentence': my_sentence})


@login_required
def dashboard_tr(request):
    my_suggests = Suggest.objects.filter(mojri=request.user)
    logger.error('Test log error')
    return render(request, 'translator_dashboard.html', {'my_suggests': my_suggests})


@login_required
def check_suggest(request, sentence_id):
    sentence = get_object_or_404(Sentence, id=sentence_id)
    suggests = Suggest.objects.filter(sentence_id=sentence.id)
    if request.method == "POST":
        suggest_id = request.POST.get('suggest_id')
        sentence_id = request.POST.get('sentence_id')
        # check if suggest_id exist in sentence
        suggests_count = Sentence.objects.filter(id=sentence_id, suggest__id=suggest_id,
                                                 suggest__status_id=1).count()
        if suggests_count == 1:
            suggest = Suggest.objects.get(id=suggest_id)
            # update status of selected suggest
            Suggest.objects.filter(id=suggest_id).update(status_id=SuggestEnum.Accept.value)
            # update sentence status
            Sentence.objects.filter(id=sentence_id).update(status_id=SentenceEnum.Processing.value,
                                                           translator=suggest.mojri)
            # update another suggest to reject
            reject_suggests = Suggest.objects.filter(sentence_id=sentence_id).exclude(sentence_id=sentence_id,
                                                                                      status_id=2)
            for reject_suggest in reject_suggests:
                Suggest.objects.filter(id=reject_suggest.id).update(status_id=SuggestEnum.Reject.value)
            return redirect('dashboard:dashboard_ap')
        return redirect('business:home')
    else:
        return render(request, 'check_suggests.html', {"sentence": sentence,
                                                       "suggests": suggests})


@login_required
def sentence_detail_dashboard(request, sentence_id, sentence_title):
    sentence = get_object_or_404(Sentence, id=sentence_id)
    accept_suggest = Suggest.objects.filter(sentence_id=sentence.id, status=SuggestEnum.Accept.value)
    judgments = Judgment
    suggest = Suggest
    try:
        suggest = Suggest.objects.get(sentence_id=sentence.id, status=SuggestEnum.Accept.value)
        judgments = Judgment.objects.filter(suggest_id=suggest.id)
    except:
        pass
    if request.method == "POST" and 'complete_file_btn' in request.POST:
        form_file = EditCompleteFileForm(request.POST, request.FILES, instance=suggest)
        if form_file.is_valid():
            suggest = form_file.save(commit=False)
            suggest.upload_time = datetime.datetime.now()
            suggest.save()
            # update sentence status
            Sentence.objects.filter(id=sentence.id).update(status_id=SentenceEnum.Completed.value)
            return redirect("dashboard:dashboard_tr")
    elif request.method == "POST" and 'judgment_btn' in request.POST:
        form_judgment = SubmitJudgmentForm(request.POST)
        if form_judgment.is_valid():
            judgment = form_judgment.save(commit=False)
            judgment.judgment_user = request.user
            judgment.suggest = suggest
            judgment.save()
            return redirect("business:home")
    else:
        form_file = EditCompleteFileForm(instance=suggest)
        form_judgment = SubmitJudgmentForm()
    return render(request, 'sentence_detail_dashboard.html', {"sentence": sentence,
                                                              "accept_suggest": accept_suggest,
                                                              "form_file": form_file,
                                                              "form_judgment": form_judgment,
                                                              "judgments": judgments})

dashboard/templates/applicant_dashboard.html
{% extends 'base.html' %}
{% block title %} onesentence - خانه {% endblock %}
{% block content %}

 <h1>داشبورد درخواست کننده</h1>
<h3>همه جمله ها</h3>
    <table border="1">
     <thead>
        <td>
         کد جمله
        </td>
        <td>
          عنوان
        </td>
        <td>
          تعداد کاراکترها
        </td>
        <td>
         زمان ثبت
        </td>
        <td>
         تعداد پیشنهادات
        </td>
        <td>
            وضعیت
        </td>
        <td>
           مترجم
        </td>
        <td>
            بررسی پیشنهادات
        </td>
     </thead>
     <tbody>
     {% for sentence in my_sentence %}
        <tr>
            <td>
             {{ sentence.id }}
            </td>
           <td>
               <a href="{% url 'dashboard:sentence_detail_dashboard' sentence.id sentence.title %}">{{ sentence.title }}</a>
           </td>
           <td>
            {{ sentence.word_count }}
           </td>
           <td>
            {{ sentence.create_time }}
           </td>
           <td>
            {{ sentence.num_suggests }}
           </td>
            <td>
            {{ sentence.status }}
            </td>
           <td>
               {% if  sentence.translator %}
               <a href="#"> {{ sentence.translator }} </a>
               {% else %}
                هنوز انتخاب نشده
               {% endif %}
           </td>
            <td>
                {% if sentence.status_id == 2 and  sentence.num_suggests > 0%}
                <a href="{% url 'dashboard:check_suggest' sentence.id%}">بررسی پیشنهادات</a>
                {% else %}
                -
                {% endif %}
            </td>
     </tr>
     {% endfor %}
     </tbody>
    </table>
{% endblock %}

dashboard/templates/check_suggests.html
{% extends 'base.html' %}
{% block title %} onesentence - بررسی پیشنهادات {% endblock %}
{% block content %}
    <h1>بررسی پیشنهادات</h1>
    <hr />
    <div style="border:1px solid gray; margin:15px;">
            عنوان:
            <a href="#">{{ sentence.title }}</a>
            <br />
            متن اصلی:
            <span> {{sentence.content_text}} </span>
            <br />
            کاربر:
            <a href="#">{{ sentence.user }}</a>
            <br >
            زمان ثبت:
            <span>{{ sentence.create_time }}</span>
            <br />
            تخصص:
            <span> {{sentence.takhasos.title }} </span>
            <br />
            تعداد کاراکترها:
            <span> {{sentence.word_count}} </span>
            <br />
            مهلت انجام:
            <span> {{sentence.mohlat_rooz }} روز</span>
            <span> {{sentence.mohlat_saat }} ساعت</span>
            <br />
            {% for suggest in suggests %}
            <div style="background-color:lightgray; margin:5px; padding:5px;">
                مجری:
                <span>{{ suggest.mojri }}</span>
                <br />
                مبلغ پیشنهادی:
                <span>{{ suggest.mablagh_pishnahadi }}</span>
                <br />
                توضیحات:
                <span>{{ suggest.description }}</span>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sentence_id" value="{{ sentence.id }}"/>
                    <input type="hidden" name="suggest_id" value="{{ suggest.id }}"/>
                    <button type="submit">تایید پیشنهاد</button>
                </form>
            </div>
            {% endfor %}
        </div>
{% endblock %}

dashboard/templates/sentence_detail_dashboard.html
{% extends 'base.html' %}
{% block title %} onesentence - جزییات جمله {% endblock %}
{% block content %}
    <h1>جزییات جمله</h1>
    <hr />
    <div style="border:1px solid gray; margin:15px;">
        عنوان:
        <a href="#">{{ sentence.title }}</a>
        <br />
        متن اصلی:
        <span> {{sentence.content_text}} </span>
        <br />
        زمان ثبت:
        <span>{{ sentence.create_time }}</span>
        <br />
        تخصص:
        <span> {{sentence.takhasos.title }} </span>
        <br />
        تعداد کاراکترها:
        <span> {{sentence.word_count}} </span>
        <br />
        درخواست کننده:
        <a href="#"> {{sentence.user}} </a>
        <br />
        مهلت انجام:
        <span> {{sentence.mohlat_rooz }} روز</span>
        <span> {{sentence.mohlat_saat }} ساعت</span>
        <br />
        <span class="status">وضعیت جمله:</span>
        <span class="status">{{ sentence.status }}</span>
        <br />
        <span class="status">وضعیت پرداخت:</span>
        <span class="status">{{ sentence.payment_status }}</span>
        {% if accept_suggest %}
            <h3>پیشنهاد تایید شده
            </h3>
            <div style="background-color:lightgray; margin:5px; padding:5px;">
                {% for suggest in accept_suggest %}
                    مجری:
                    <span>{{ suggest.mojri }}</span>
                    <br />
                    مبلغ پیشنهادی:
                    <span>{{ suggest.mablagh_pishnahadi }}</span>
                    <br />
                    توضیحات:
                    <span>{{ suggest.description }}</span>
                    <br />
                    فایل تحویلی:
                    {% if request.user == suggest.mojri %}
                    <span>{{ suggest.completeFile }}</span>
                    {% elif sentence.status.id == 4 %}
                        {% if sentence.payment_status.id == 2%}
                            <a href="{{suggest.completeFile}}">دانلود ترجمه</a>
                        {% else %}
                            <form method="get" action="/payment/">
                                <input type="hidden" name="sentence" value="{{ sentence.id }}">
                                <input type="hidden" name="suggest" value="{{ suggest.id }}">
                                <br />
                                <input type="submit" value="پرداخت هزینه و دانلود فایل"/>
                            </form>
                        {% endif  %}
                    {% endif  %}
                    {% if request.user == suggest.mojri %}
                        <h3>ارسال فایل ترجمه</h3>
                        <form method="post" action=""  enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form_file.as_p }}
                            <br />
                            <input type="submit" name="complete_file_btn" value="ارسال فایل"/>
                        </form>
                    {% endif  %}
                {% endfor %}
            </div>
            <h3>درخواست داوری</h3>
                {% if judgments %}
                    <div>
                    {% for judgment in judgments %}
                        درخواست کننده:
                        {{ judgment.judgment_user }}
                        <br/>
                        تاریخ ثبت:
                        {{ judgment.create_time }}
                        <br/>
                        توضیحات:
                        {{ judgment.judgment_description }}
                        <br/>
                        رای داور به نفع:
                        {{ judgment.judgment_won_user }}
                                                <br/>
                        توضیحات داور:
                        {{ judgment.davar_description }}
                    {% endfor %}
                    </div>
                {% else %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form_judgment.as_p }}
                        <input type="submit" name="judgment_btn" value="ثبت درخواست داوری"/>
                    </form>
                {% endif %}
        {% else %}
            <h3>هنوز پیشنهادی تایید نشده</h3>
        {% endif %}
    </div>
{% endblock %}

dashboard/templates/translator_dashboard.html
{% extends 'base.html' %}
{% block title %} onesentence - خانه {% endblock %}
{% block content %}

 <h1>داشبورد مترجم</h1>
<h3>همه پیشنهادهای من</h3>
    <table border="1">
     <thead>
        <td>
         کد جمله
        </td>
        <td>
          عنوان
        </td>
        <td>
          تعداد کاراکترها
        </td>
        <td>
         توضیحات من
        </td>
        <td>
         زمان ثبت
        </td>
        <td>
         پیشنهاد من
        </td>
        <td>
          وضعیت پیشنهاد
        </td>
        <td>
          وضعیت تحویل فایل
        </td>
     </thead>
     <tbody>
     {% for suggest in my_suggests %}
        <tr>
            <td>
             {{ suggest.sentence.id }}
            </td>
           <td>
            <a href="{% url 'dashboard:sentence_detail_dashboard' suggest.sentence.id suggest.sentence.title %}">{{ suggest.sentence.title }}</a>
           </td>
           <td>
            {{ suggest.sentence.word_count }}
           </td>
           <td>
            {{ suggest.description }}
           </td>
           <td>
            {{ suggest.sentence.create_time }}
           </td>
           <td>
            {{ suggest.mablagh_pishnahadi }}
           </td>
           <td>
            {{ suggest.status }}
           </td>
            <td>
                {{ suggest.sentence.status }}
            </td>
     </tr>
     {% endfor %}
     </tbody>
    </table>


{% endblock %}